#!/usr/bin/env bash

OS=$(uname -s)

case "$OS" in
    "Darwin")
        cp ./overrides/mac/.iterm2_shell_integration.fish ./iterm2/.iterm2_shell_integration.fish
        /opt/homebrew/bin/stow -vt ~ yabai
        ;;
    *)
        echo "Unable to determine OS. Setup iTerm2 manually."
        ;;
esac

stow -vt ~ aliases
stow -vt ~ fish
stow -vt ~ gh
stow -vt ~ git
stow -vt ~ hammerspoon
stow -vt ~ karabiner
stow -vt ~ kitty
stow -vt ~ nvim
stow -vt ~ ssh
stow -vt ~ tmux
stow -vt ~ vscode
stow -vt ~ i3
stow -vt ~ zsh
stow -vt ~ zk
cp git/hooks/post-commit .git/hooks/

# Remove the hooks directory that is stowed
rm ./iterm2/.iterm2_shell_integration.fish
cd ~
rm -rf hooks
