# NOTEBOOK SETTINGS
[notebook]
dir = "~/zettelkasten"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
# filename = "{{id}}-{{slug title}}"
filename = "{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs.
id-case = "lower"

# EXTRA VARIABLES
[extra]
author = "Gowtham UJ"

# GROUP OVERRIDES
[group.journal]
paths = ["journal/weekly", "journal/daily"]

[group.journal.note]
filename = "{{format-date now '%m-%d-%Y'}}"
template = "journal.md"

[group.book]
[group.book.note]
filename = "{{format-date now '%m-%d-%Y'}}-book-notes"
template = "book.md"

[group.podcast]
[group.podcast.note]
filename = "{{format-date now '%m-%d-%Y'}}-podcast-notes"
template = "podcast.md"

[group.work]
paths = ["work/*"]

[group.work.note]
filename = "{{format-date now '%m-%d-%Y'}}-work-update"
template = "work-update.md"

[group.meeting-notes]
[group.meeting-notes.note]
filename = "{{format-date now '%m-%d-%Y'}}-{{title}}"
template = "meeting-notes.md"

[group.joe]
paths = ["work/joe/*"]

[group.joe.note]
filename = "joe-{{format-date now '%m-%d-%Y'}}"
template = "joe-1-1.md"

[group.ankit]
paths = ["work/ankit/*"]

[group.ankit.note]
filename = "ankit-{{format-date now '%m-%d-%Y'}}"
template = "ankit-1-1.md"

[group.mos-lead]
paths = ["work/1-1/*"]

[group.mos-lead.note]
filename = "{{format-date now '%m-%d-%Y'}}"
template = "mos-1-1.md"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true
link-format = "wiki"

# EXTERNAL TOOLS
[tool]
# Default editor used to open notes.
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

# Default shell used by aliases and commands.
# shell = "/bin/bash"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
# Create/open dated file under work dir to provide updates
su = "zk new --group work work"
# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"
# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
# This needs to be added to the individual notes config.toml file as well, as the default is different
note-filter-text = "{{title}} {{path}}"
