source ~/.vim/mathworks-ruby.vim
source ~/.vim/plugin-config.vim
source ~/.vim/plugins.vim
source ~/.vim/settings.vim
source ~/.vim/shortcuts.vim
source ~/.vim/tmux-config.vim

" This needs to be in here, so that you don't have to reload vim config once
" opened.
source ~/.vim/plugin-shortcuts.vim

" This needs to be in the end to override language specific configs.
source ~/.vim/language.vim
